### ISSUE TITLE
Issue while viewing products from the link in the email

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/woocommerce-product-stock-alert#105]
One user has subscribed to an out of stock product. He receives an email after subscription. From the email when he clicks on the product link if he has a vendor role then gets redirected to WordPress backend and if he has customer role he gets redirected to the My account page. 
But the user should get redirected to the single product page.

**Comment by kpanosgr** [comment]
Had the same problem. Commit seems to solves it.
