### ISSUE TITLE
Additional fields not targeted (javascript)

### ISSUE THREAD

**Issue by kpanosgr** [multivendorx/woocommerce-product-stock-alert#107]
So I wanted to add additional field to the form, e.g. phone
Added the following code in functions.php :

```
function add_alert_phone_field( $array ) {
	$array['stock_alert_phone'] = array(
		'type'			=>	'text',
		'class'			=>	'stock_alert_phone',
		'placeholder'	=>	__('Enter your mobile phone number', 'woocommerce-product-stock-alert')
		);
    return $array;
}
add_filter('woo_stock_alert_fileds_array', 'add_alert_phone_field');

function push_additional_fields( $text ) {
    return ['stock_alert_phone'];
}
add_filter('woocommerce_product_stock_alert_form_additional_fields', 'push_additional_fields');

add_action( 'woocommerce_email_footer', 'woocommerce_email_footer_phone_field' );
function woocommerce_email_footer_phone_field(){
	$alert_phone = '';
	if ( ! empty($_POST['stock_alert_phone'])){
		$alert_phone = $_POST['stock_alert_phone'];
		//show field here in HTML
	 }
}
```

Everything works fine, but the **stock_alert_phone** field is not passed by the form. From a little research i found that in the js files(assets\frontend\js), it cannot be targeted. Code is this part:

`for (var i=0; i<woo_stock_alert_script_data.additional_fields.length; i++){
                    stock_alert[woo_stock_alert_script_data.additional_fields[i]] = $(this).parent().find('.'+woo_stock_alert_script_data.additional_fields[i]).val();
                }`

So i had to remove $(this).parent().find, and replace it with only $ :
`for (var i=0; i<woo_stock_alert_script_data.additional_fields.length; i++){
                    stock_alert[woo_stock_alert_script_data.additional_fields[i]] = $('.'+woo_stock_alert_script_data.additional_fields[i]).val();
                }`

**Comment by moumitahalder** [comment]
we have modified the code and here is the updated plugin file https://www.transfernow.net/dl/20231221DitX6b8e

Install this file and run the above code, the addional field will be displayed.

If you need any further help, please do let us know.
