### ISSUE TITLE
No notification if you use a stock manager?



### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/woocommerce-product-stock-alert#19]
Of stock is updated using any other third party plugin, then mail is not getting triggered

**Comment by moumitahalder** [comment]
https://wordpress.org/plugins/woocommerce-stock-manager/

**Comment by demaya** [comment]
@moumitahalder any update on this? We use BillBee as external Stock manager (guess REST-API) and restocking doesn't trigger an email.

**Comment by jmargel74** [comment]
Getting the same issue.  moumitahalder that plugin did work with this one however now it's not triggering the emails to be sent.  After using a bulk editor you have to manually go into the product and click the update button for the emails to be sent.

**Comment by demaya** [comment]
Any update on this @moumitahalder ?

**Comment by abhirup97** [comment]
note: default WooCommerce actions like woocommerce_product_set_stock and woocommerce_variation_set_stock should work for this
