### ISSUE TITLE
Unnecessary wp block editor assets in frontend

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/woocommerce-product-stock-alert#243]
Looks like method enqueue_block_assets() in StockManager class should check if request is admin or preview before wp_enqueue_script() call.

Currently this is causing unnecessary script bloat in frontend and request to /wp-json/wp/v2/users/me?context=edit&_locale=user which fails miserably with 401 error if user is not logged in.

**Comment by UjjwalGorai** [comment]
Fixed this issue with Pull Request: [https://github.com/multivendorx/woocommerce-product-stock-alert/pull/244](url)
