### ISSUE TITLE
 Uncaught TypeError:

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/woocommerce-product-stock-alert#41]
E_ERROR (1): Uncaught TypeError: Unsupported operand types: int + string in /wp-content/plugins/woocommerce-product-stock-alert/classes/class-woo-product-stock-alert-ajax.php:220
Stack trace:
#0 /wp-includes/class-wp-hook.php(303): WOO_Product_Stock_Alert_Ajax->stock_alert_function()
#1 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /wp-admin/admin-ajax.php(187): do_action()
#4 {main}
  thrown in 
/wp-content/plugins/woocommerce-product-stock-alert/classes/class-woo-product-stock-alert-ajax.php on line 220

**Comment by Ritwik460** [comment]
#41

**Comment by Ritwik460** [comment]
#41
